// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entity
{
    [Table("tblElanat", Schema = "CSS")]
    public partial class Elanat
    {
        [Key]
        [Column("tblElanatId")]
        public int ElanatId { get; set; }
        [StringLength(1000)]
        public string MessageTopic { get; set; }
        public string MessageText { get; set; }
        [StringLength(10)]
        public string DateFrom { get; set; }
        [StringLength(10)]
        public string DateTo { get; set; }
        [StringLength(250)]
        public string DisplayGroup { get; set; }
        public int? LevelId { get; set; }
        [StringLength(250)]
        public string FileUploadPath { get; set; }
        [Column("isShow")]
        public bool? IsShow { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        
    }
}